theme: jekyll-theme-slate
markdown: kramdown

kramdown:
  math_engine: sskatex
  math_engine_opts:
    katex_js: '/tmp/katex.min.js'
    katex_opts:
      throwOnError: false

  syntax_highlighter: rouge
  header_offset: 1 # h1 becomes h2 (h1 is title)

  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

